{
    'name': 'All in one VAT reports',
    'version': '13.0.5',
    'category': 'Accounting',
    'summary': 'Extend the function of Odoo VAT return and addition of new VAT report',
    'author': 'TAXDOTCOM',
    'website': 'http://taxdotcom.org/',
    'maintainer': 'Muhammad Younis',
    'depends': ['account','stock'],
    'data': [
        'views/tax_payment_adjustment.xml',
        'views/inv_bill_format.xml',
        'reports/vat_report_wizard.xml',
        'views/account.xml',
        'views/account_tax.xml',
        'views/account_move.xml',
    ],
    'installable': True,
    'auto_install': False,
    'price': 50.00,
    'currency': 'EUR',
    'images': ['static/description/image.jpeg'],
    'license': 'OPL-1',
}
